"""Abstract interfaces for future Phase detection, tracking, face recognition, and alerting."""

import abc
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple
import numpy as np


@dataclass
class DetectionBox:
    """Bounding box for detected object."""
    bbox: Tuple[int, int, int, int]  # (x, y, w, h)
    confidence: float
    class_name: str  # "KNOWN_PERSON" or "UNKNOWN_PERSON"
    pane_id: str
    person_id: Optional[str] = None
    person_name: Optional[str] = None
    tag: Optional[str] = None
    is_known: bool = False
    snapshot_base64: Optional[str] = None


@dataclass
class TrackedObject:
    """Tracked entity across consecutive frames."""
    track_id: int
    pane_id: str
    camera_label: str
    class_name: str
    current_bbox: Tuple[int, int, int, int]
    trajectory: List[Tuple[int, int]] = field(default_factory=list)
    is_known_person: Optional[bool] = None
    person_name: Optional[str] = None


@dataclass
class AlertEvent:
    """Alert generated by real-time rule engine."""
    alert_id: str
    timestamp: float
    pane_id: str
    camera_label: str
    rule_name: str
    severity: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    description: str
    evidence_snapshot: Optional[np.ndarray] = None
    vlm_enrichment: Optional[Dict[str, Any]] = None


class PersonDetector(abc.ABC):
    """Detects persons inside extracted pane images."""

    @abc.abstractmethod
    def detect_persons(self, pane_image: np.ndarray, pane_id: str) -> List[DetectionBox]:
        pass


class Tracker(abc.ABC):
    """Tracks detected objects across frames."""

    @abc.abstractmethod
    def update(self, detections: List[DetectionBox], timestamp: float) -> List[TrackedObject]:
        pass


class FaceRecognizer(abc.ABC):
    """Identifies known vs unknown persons."""

    @abc.abstractmethod
    def recognize_face(self, face_crop: np.ndarray) -> Tuple[Optional[str], float, bool]:
        """Returns (person_name, confidence, is_known)."""
        pass


class RuleEngine(abc.ABC):
    """Evaluates spatial zone rules, loitering, and intrusion."""

    @abc.abstractmethod
    def evaluate_rules(self, tracked_objects: List[TrackedObject], timestamp: float) -> List[AlertEvent]:
        pass


class AlertManager(abc.ABC):
    """Dispatches alerts to downstream subscribers."""

    @abc.abstractmethod
    def dispatch_alert(self, alert: AlertEvent) -> None:
        pass


class EvidenceStore(abc.ABC):
    """Stores alert snapshots and video clips."""

    @abc.abstractmethod
    def store_evidence(self, alert: AlertEvent) -> str:
        """Returns evidence URI / path."""
        pass
